const Discord = require('discord.js');
const bot = new Discord.Client();

bot.on('ready', () => {
  console.log('I am ready!');
  bot.user.setPresence({ game: { name: 'with oden 🍢', type: 0 } })
});

const prefix ="cb!"




bot.on('message', message => {
  if(message.author.bot)return;


var rand = Math.round(Math.random() * (8 - 1) + 1)
var odenmessage = [ '',
            "Here's some oden! :oden:",
             message.author.username + "! :oden: !",
            "Hey " +  message.author.username + " Don't forget to pay your tab, you idjit. . . ",
            'IF YOU WANT ODEN PAY YOUR DAMN TAB FIRST',
            ":oden: :oden: :oden:",
            "ODEN IS THE BEST",
            "do you want oden, " + message.author.username + "?", 
            ":oden: :sparkles:"
              ];

if(message.content.toLowerCase().includes( ['bepsi'] ) || message.content.toLowerCase().includes( ['pepsi'] ) ){
       message.react(":bepsi:403237730919645224");
   }

if(message.content.toLowerCase().includes( ['oden'] ) ){
     if(message.content.toLowerCase().includes( [' oden '] )|| message.content.toLowerCase().startsWith( ['oden '] ) ){
        message.channel.sendMessage( odenmessage[rand] );
   }
     else  message.react("🍢");
   }   

 if(message.content.toLowerCase().includes( ['odenbot'] ) ){
       message.react("💛");
   }  


  if (message.content.startsWith(prefix + "shiny"))  {
    message.channel.sendMessage('my wonderful creator S H I N Y, a very shiny person');
  }


  
if (message.content.startsWith(prefix + "dick"))  {
message.channel.sendMessage(" ", {
    file: "https://cdn.discordapp.com/attachments/345298931581976606/400904845793427467/unknown.png"// Or replace with FileOptions object https://cdn.discordapp.com/attachments/331650068383924226/336928757405319168/unknown.png","
});
}


if (message.content.startsWith(prefix + "help"))  {
message.channel.sendMessage(":sparkles: :oden: A  **Team Kara**  Bot   |   Prefix: `cb!`\nCurrent commands: `kara` , `chibita` , `kinniku` , `oso` , `gun` , `clap` ,  `oden` , `heh` , `dick` , `house` |  Command example: `cb!kara`");
}


if (message.content.toLowerCase().startsWith(prefix + "oden <@!")) {
  var odene= message.cleanContent.replace("cb!oden @", "")
  message.channel.sendMessage( ":oden:  |  **" + message.author.username + "** has given **" + odene + "** oden!");
}



var domymath = Math.round(Math.random() * (5 - 1) + 1)
var gunmessage = [ "https://i.imgur.com/TqwGJcx.jpg",
"https://i.imgur.com/QyB95GR.jpg",
"https://i.imgur.com/g3P1DR0.png",
"https://i.imgur.com/EAfnQGi.jpg",
"https://i.imgur.com/qAJVv5B.png" 
];


  if (message.content.startsWith(prefix + "gun"))  {
    var saying= message.cleanContent.replace("cb!gun", " ")
message.channel.sendMessage(saying, {
    file: gunmessage[domymath] 
});
}

  if (message.content.startsWith(prefix + "house"))  {
    var saying= message.cleanContent.replace("cb!house", " ")
message.channel.sendMessage("┏┓\n┃┃╱╲ In this \n┃╱╱╲╲ house \n╱╱╭╮╲╲ we love \n▔▏┗┛▕▔ & appreciate \n╱▔▔▔▔▔▔▔▔▔▔╲ \n"+saying+"\n╱╱┏┳┓╭╮┏┳┓ ╲╲ \n▔▏┗┻┛┃┃┗┻┛▕▔ ");
}


var count = Math.round(Math.random() * (969 - 1) + 1)
var randomkara = ["https://i.imgur.com/A7lmcTR.jpg",
"https://i.imgur.com/4UlnR9G.jpg",
"https://i.imgur.com/OjNUShk.jpg",
"https://i.imgur.com/pBtV7a1.jpg",
"https://i.imgur.com/wfLSw0l.jpg",
"https://i.imgur.com/f4nUiug.png",
"https://i.imgur.com/Rwcge7V.jpg",
"https://i.imgur.com/ljljyBh.jpg",
"https://i.imgur.com/ZFfgSZI.jpg",
"https://i.imgur.com/q3xqBGH.jpg",
"https://i.imgur.com/SNAGTse.jpg",
"https://i.imgur.com/6WIAytk.jpg",
"https://i.imgur.com/7u7O43t.jpg",
"https://i.imgur.com/a5zemW4.jpg",
"https://i.imgur.com/osMuO8V.jpg",
"https://i.imgur.com/z2QBMSD.jpg",
"https://i.imgur.com/j7cHaBR.jpg",
"https://i.imgur.com/VtEXJ56.jpg",
"https://i.imgur.com/Oo1xEDV.jpg",
"https://i.imgur.com/cg8ADoW.jpg",
"https://i.imgur.com/O9vnOfA.jpg",
"https://i.imgur.com/v0ckFUb.jpg",
"https://i.imgur.com/g4EjQBw.jpg",
"https://i.imgur.com/CaZvDUy.jpg",
"https://i.imgur.com/WZAvIpD.jpg",
"https://i.imgur.com/0PtJkTc.jpg",
"https://i.imgur.com/XeCHIRI.jpg",
"https://i.imgur.com/nKsDuvB.jpg",
"https://i.imgur.com/RSVKfAf.jpg",
"https://i.imgur.com/xI7cB4w.jpg",
"https://i.imgur.com/AdpZRlI.jpg",
"https://i.imgur.com/F6c7E23.jpg",
"https://i.imgur.com/oGcY0dC.jpg",
"https://i.imgur.com/j3rWKVd.jpg",
"https://i.imgur.com/kedhVQR.jpg",
"https://i.imgur.com/Ni6yR9z.jpg",
"https://i.imgur.com/itmTQzw.jpg",
"https://i.imgur.com/QGq9baf.jpg",
"https://i.imgur.com/5I4tayj.jpg",
"https://i.imgur.com/mO4IVVB.jpg",
"https://i.imgur.com/OFPrRLp.jpg",
"https://i.imgur.com/pZ7PvcD.jpg",
"https://i.imgur.com/3mdyQ9g.jpg",
"https://i.imgur.com/uZW2eVF.jpg",
"https://i.imgur.com/ayJu6r4.jpg",
"https://i.imgur.com/89sbuAR.jpg",
"https://i.imgur.com/X77uJHj.jpg",
"https://i.imgur.com/Sem3XHZ.jpg",
"https://i.imgur.com/euWrNNs.jpg",
"https://i.imgur.com/DwZ6oNC.jpg",
"https://i.imgur.com/YYgsa7b.jpg",
"https://i.imgur.com/pVGAsaL.png",
"https://i.imgur.com/ilE2FyS.jpg",
"https://i.imgur.com/4rllPsn.jpg",
"https://i.imgur.com/yPoapEA.jpg",
"https://i.imgur.com/U4xRgEt.jpg",
"https://i.imgur.com/ZVGfWSE.jpg",
"https://i.imgur.com/KtPlzlN.jpg",
"https://i.imgur.com/ZWGpiuv.jpg",
"https://i.imgur.com/wVATnBo.jpg",
"https://i.imgur.com/OlJsjda.jpg",
"https://i.imgur.com/1iNI2xT.jpg",
"https://i.imgur.com/CIC0BQ0.jpg",
"https://i.imgur.com/IInG4xs.jpg",
"https://i.imgur.com/vfDDHap.jpg",
"https://i.imgur.com/69yY6fz.jpg",
"https://i.imgur.com/VI6uenB.jpg",
"https://i.imgur.com/eAkNs8Q.jpg",
"https://i.imgur.com/dI5SK5l.jpg",
"https://i.imgur.com/bbfYEy5.jpg",
"https://i.imgur.com/4gxTPbd.jpg",
"https://i.imgur.com/2ffxXzZ.jpg",
"https://i.imgur.com/MhQHOI7.jpg",
"https://i.imgur.com/M3T69OU.jpg",
"https://i.imgur.com/alaSGSQ.jpg",
"https://i.imgur.com/wGwlpDh.jpg",
"https://i.imgur.com/nlCCpRh.jpg",
"https://i.imgur.com/Lm6EYDq.jpg",
"https://i.imgur.com/EP5dlV2.jpg",
"https://i.imgur.com/0IrE3od.jpg",
"https://i.imgur.com/gdGQ71b.jpg",
"https://i.imgur.com/XD5UINk.jpg",
"https://i.imgur.com/dbS4bTd.jpg",
"https://i.imgur.com/u0fx462.jpg",
"https://i.imgur.com/uV576Ea.jpg",
"https://i.imgur.com/6I5rYQk.jpg",
"https://i.imgur.com/HkRd9d5.jpg",
"https://i.imgur.com/aoPLTOn.jpg",
"https://i.imgur.com/FWVh6BD.jpg",
"https://i.imgur.com/Rf9Z5Gu.jpg",
"https://i.imgur.com/zhNDkFf.jpg",
"https://i.imgur.com/u8ria8C.jpg",
"https://i.imgur.com/UplZ4yJ.jpg",
"https://i.imgur.com/7OXGgpa.jpg",
"https://i.imgur.com/OMcwY73.jpg",
"https://i.imgur.com/3rsMZIJ.jpg",
"https://i.imgur.com/DOyd4MS.jpg",
"https://i.imgur.com/ezGsAzv.jpg",
"https://i.imgur.com/ocB2TFZ.jpg",
"https://i.imgur.com/h5l3iBl.jpg",
"https://i.imgur.com/F6ItIJt.jpg",
"https://i.imgur.com/HsuFp3r.jpg",
"https://i.imgur.com/XIIhJfW.jpg",
"https://i.imgur.com/NURgWbT.jpg",
"https://i.imgur.com/BgpjbmC.jpg",
"https://i.imgur.com/6ZM0Gp9.jpg",
"https://i.imgur.com/fgq9t0M.jpg",
"https://i.imgur.com/zaTck6z.jpg",
"https://i.imgur.com/p27XPVJ.jpg",
"https://i.imgur.com/XjfbNZN.jpg",
"https://i.imgur.com/1ywGf0k.jpg",
"https://i.imgur.com/MzmNSye.jpg",
"https://i.imgur.com/37BYid4.jpg",
"https://i.imgur.com/ar8OUKU.jpg",
"https://i.imgur.com/cnJ8W5O.jpg",
"https://i.imgur.com/C2geuvT.jpg",
"https://i.imgur.com/DDkisWL.jpg",
"https://i.imgur.com/t41jH9A.jpg",
"https://i.imgur.com/ISLuioy.jpg",
"https://i.imgur.com/cNDrIf4.jpg",
"https://i.imgur.com/gLE4KX2.jpg",
"https://i.imgur.com/lHAU3pd.jpg",
"https://i.imgur.com/eUU4xZ0.jpg",
"https://i.imgur.com/X6HaCUw.jpg",
"https://i.imgur.com/cAx2VLW.jpg",
"https://i.imgur.com/xwPa8lo.jpg",
"https://i.imgur.com/e2IvINV.jpg",
"https://i.imgur.com/L4LnAJ1.jpg",
"https://i.imgur.com/zRelGVa.jpg",
"https://i.imgur.com/457TfCq.jpg",
"https://i.imgur.com/pUJyRrL.jpg",
"https://i.imgur.com/TzQCdOz.jpg",
"https://i.imgur.com/2YifK4f.jpg",
"https://i.imgur.com/PUBIO7U.jpg",
"https://i.imgur.com/km6jvJL.jpg",
"https://i.imgur.com/k0Ej0MT.jpg",
"https://i.imgur.com/xAZrKNk.jpg",
"https://i.imgur.com/6YoF8NQ.jpg",
"https://i.imgur.com/WJe9ODw.jpg",
"https://i.imgur.com/DxAFeIZ.jpg",
"https://i.imgur.com/xIFcoB1.jpg",
"https://i.imgur.com/IW3OWZh.jpg",
"https://i.imgur.com/rWoTJu1.jpg",
"https://i.imgur.com/ozpHwiY.jpg",
"https://i.imgur.com/JLX8ZD0.jpg",
"https://i.imgur.com/ctlPVfF.jpg",
"https://i.imgur.com/smM4UYd.jpg",
"https://i.imgur.com/iHQ353V.jpg",
"https://i.imgur.com/X6f3T3Q.jpg",
"https://i.imgur.com/HC6gPFU.png",
"https://i.imgur.com/q1dYPjc.jpg",
"https://i.imgur.com/SFwrEsQ.jpg",
"https://i.imgur.com/jzL2eoc.jpg",
"https://i.imgur.com/IVAbCG0.jpg",
"https://i.imgur.com/TRZzrGd.jpg",
"https://i.imgur.com/ba5fLDB.jpg",
"https://i.imgur.com/XB1lW21.jpg",
"https://i.imgur.com/BHJljMI.jpg",
"https://i.imgur.com/Ed0M7T6.jpg",
"https://i.imgur.com/UgeIbma.jpg",
"https://i.imgur.com/frgGl56.jpg",
"https://i.imgur.com/zqnWt2u.jpg",
"https://i.imgur.com/GTDC9mc.jpg",
"https://i.imgur.com/3WVWlfq.jpg",
"https://i.imgur.com/A4gdNnz.jpg",
"https://i.imgur.com/54HTa3y.jpg",
"https://i.imgur.com/UHZfd0h.jpg",
"https://i.imgur.com/rxa1xHX.jpg",
"https://i.imgur.com/Srybxye.jpg",
"https://i.imgur.com/WVl6h3K.jpg",
"https://i.imgur.com/bIjPVS3.gif",
"https://i.imgur.com/S7DE5AC.jpg",
"https://i.imgur.com/jjI8hdx.jpg",
"https://i.imgur.com/R01kkgR.jpg",
"https://i.imgur.com/vzRWsSR.jpg",
"https://i.imgur.com/njsudOv.jpg",
"https://i.imgur.com/qIfFre7.jpg",
"https://i.imgur.com/FifYLQe.jpg",
"https://i.imgur.com/4e4lKHk.jpg",
"https://i.imgur.com/qQN1f8k.jpg",
"https://i.imgur.com/boZ8oVX.jpg",
"https://i.imgur.com/D9Aykqd.jpg",
"https://i.imgur.com/oW4LCo7.jpg",
"https://i.imgur.com/QE29zYJ.jpg",
"https://i.imgur.com/F2dNrkW.jpg",
"https://i.imgur.com/bvrfZAA.jpg",
"https://i.imgur.com/Nj6T6yj.jpg",
"https://i.imgur.com/QPSk9A8.jpg",
"https://i.imgur.com/Ucd863k.png",
"https://i.imgur.com/Cvjajkv.jpg",
"https://i.imgur.com/cFnPjje.jpg",
"https://i.imgur.com/cntRkJx.png",
"https://i.imgur.com/dc3dcW4.jpg",
"https://i.imgur.com/m8OVESS.jpg",
"https://i.imgur.com/2Px9Ran.png",
"https://i.imgur.com/KmK5FIx.gif",
"https://i.imgur.com/6xAH6Ce.png",
"https://i.imgur.com/W7ThVrp.jpg",
"https://i.imgur.com/FsdE2WF.jpg",
"https://i.imgur.com/e3CWzas.jpg",
"https://i.imgur.com/pf40Iyk.png",
"https://i.imgur.com/FSSlSu2.jpg",
"https://i.imgur.com/h5VfQZQ.jpg",
"https://i.imgur.com/PDhzYDD.jpg",
"https://i.imgur.com/0ODvRkQ.jpg",
"https://i.imgur.com/OPGkeEc.jpg",
"https://i.imgur.com/tkMIOeh.png",
"https://i.imgur.com/hdkHebs.jpg",
"https://i.imgur.com/rcqcOwL.jpg",
"https://i.imgur.com/cK6nvl6.jpg",
"https://i.imgur.com/74PrGLQ.jpg",
"https://i.imgur.com/pGYOg5m.jpg",
"https://i.imgur.com/aPe5JFu.jpg",
"https://i.imgur.com/Qd44jl5.png",
"https://i.imgur.com/kjDuiDq.png",
"https://i.imgur.com/bk58uv1.jpg",
"https://i.imgur.com/elj9Fqt.jpg",
"https://i.imgur.com/eMAoeag.png",
"https://i.imgur.com/BEwNIVx.jpg",
"https://i.imgur.com/OgWwg3y.jpg",
"https://i.imgur.com/pm2ufX0.jpg",
"https://i.imgur.com/Xtfpe8F.png",
"https://i.imgur.com/sIvwwGg.jpg",
"https://i.imgur.com/QKJWhTM.jpg",
"https://i.imgur.com/6RMsngI.png",
"https://i.imgur.com/vcHuzn0.png",
"https://i.imgur.com/WhSdbey.png",
"https://i.imgur.com/VRhLKss.jpg",
"https://i.imgur.com/tgS3GFJ.png",
"https://i.imgur.com/N0QDYbI.jpg",
"https://i.imgur.com/Aa2bh3n.png",
"https://i.imgur.com/2Vujgbn.png",
"https://i.imgur.com/PhZ8YXj.jpg",
"https://i.imgur.com/JXdaYF4.png",
"https://i.imgur.com/lnYItxd.jpg",
"https://i.imgur.com/bj6eZdB.png",
"https://i.imgur.com/t1Lo4rW.png",
"https://i.imgur.com/QwfJRhY.jpg",
"https://i.imgur.com/YWXCnF6.jpg",
"https://i.imgur.com/8GuPv2D.jpg",
"https://i.imgur.com/6xbp8ci.jpg",
"https://i.imgur.com/xi48IlB.jpg",
"https://i.imgur.com/4uxJO0d.jpg",
"https://i.imgur.com/CpJ68rR.png",
"https://i.imgur.com/1Cllfgn.jpg",
"https://i.imgur.com/y3D9bzQ.jpg",
"https://i.imgur.com/fmBh8HK.jpg",
"https://i.imgur.com/69euJmy.jpg",
"https://i.imgur.com/t0BoyFp.png",
"https://i.imgur.com/H8p78hF.png",
"https://i.imgur.com/hdmnWuT.png",
"https://i.imgur.com/XMwvCnv.jpg",
"https://i.imgur.com/jIuzWRw.jpg",
"https://i.imgur.com/tje2S4J.png",
"https://i.imgur.com/PVptlNx.png",
"https://i.imgur.com/hAuLddz.jpg",
"https://i.imgur.com/pFx5r6v.jpg",
"https://i.imgur.com/LFRzGZC.jpg",
"https://i.imgur.com/6Nd0ul1.png",
"https://i.imgur.com/NA38jep.png",
"https://i.imgur.com/1z1MoMn.jpg",
"https://i.imgur.com/hwwfNAU.png",
"https://i.imgur.com/jYX07v1.jpg",
"https://i.imgur.com/n0U1A2D.png",
"https://i.imgur.com/B7FZDVw.png",
"https://i.imgur.com/HqO6R7O.jpg",
"https://i.imgur.com/ZoZvxjG.jpg",
"https://i.imgur.com/vzaK7IC.png",
"https://i.imgur.com/ljorRML.jpg",
"https://i.imgur.com/K5HCMCn.jpg",
"https://i.imgur.com/pgalB2H.png",
"https://i.imgur.com/XtAYscF.jpg",
"https://i.imgur.com/y5sCJ4S.jpg",
"https://i.imgur.com/0hVITny.jpg",
"https://i.imgur.com/N2SyWWh.png",
"https://i.imgur.com/kA9SmH9.jpg",
"https://i.imgur.com/qcmmET8.jpg",
"https://i.imgur.com/TW4XCAd.jpg",
"https://i.imgur.com/QAHUXKH.png",
"https://i.imgur.com/sHQ64CH.jpg",
"https://i.imgur.com/zTn66LK.png",
"https://i.imgur.com/fCg0x5g.jpg",
"https://i.imgur.com/aVcoNOU.png",
"https://i.imgur.com/sanWX2g.png",
"https://i.imgur.com/nvnmRCw.jpg",
"https://i.imgur.com/jlg4k8w.jpg",
"https://i.imgur.com/PjsgCdf.jpg",
"https://i.imgur.com/Nbfk0rx.png",
"https://i.imgur.com/DhBFpUp.jpg",
"https://i.imgur.com/6e4G5yQ.jpg",
"https://i.imgur.com/i9U5iJk.png",
"https://i.imgur.com/mjhgv5D.jpg",
"https://i.imgur.com/N7uL94Y.jpg",
"https://i.imgur.com/3iHENbk.jpg",
"https://i.imgur.com/H5sVMCU.jpg",
"https://i.imgur.com/KJmYPBl.jpg",
"https://i.imgur.com/djnpdLs.jpg",
"https://i.imgur.com/QNXmHId.png",
"https://i.imgur.com/Zkw4nvq.png",
"https://i.imgur.com/Xtt0aA3.jpg",
"https://i.imgur.com/gQd9t7M.jpg",
"https://i.imgur.com/TNHzp9M.jpg",
"https://i.imgur.com/WDVAxex.jpg",
"https://i.imgur.com/KF4YNcY.png",
"https://i.imgur.com/Yx7IkQL.jpg",
"https://i.imgur.com/87LJt8d.jpg",
"https://i.imgur.com/hmJJPzU.png",
"https://i.imgur.com/fSjWnWq.jpg",
"https://i.imgur.com/ynwO9Kw.jpg",
"https://i.imgur.com/2ZaKpOr.jpg",
"https://i.imgur.com/7TBTTrj.jpg",
"https://i.imgur.com/3mgFpqX.png",
"https://i.imgur.com/Y0ABq3f.png",
"https://i.imgur.com/HBCTbSl.png",
"https://i.imgur.com/2xxebuF.jpg",
"https://i.imgur.com/Dbew5p8.jpg",
"https://i.imgur.com/bx6Okyw.png",
"https://i.imgur.com/PPLzoHM.jpg",
"https://i.imgur.com/4tiUBWI.jpg",
"https://i.imgur.com/GKamcLy.jpg",
"https://i.imgur.com/9LShe0J.jpg",
"https://i.imgur.com/7Yj7u7b.jpg",
"https://i.imgur.com/ijaDFRU.jpg",
"https://i.imgur.com/PwUgTC2.jpg",
"https://i.imgur.com/KO3lqtJ.png",
"https://i.imgur.com/L1OOeBy.jpg",
"https://i.imgur.com/cuRyO5B.jpg",
"https://i.imgur.com/4irwJfx.jpg",
"https://i.imgur.com/7abSrIr.png",
"https://i.imgur.com/LHzSzSR.png",
"https://i.imgur.com/RHN0uX2.png",
"https://i.imgur.com/NesplVg.jpg",
"https://i.imgur.com/VvjJRPE.png",
"https://i.imgur.com/vQ1g7eW.png",
"https://i.imgur.com/FRoYwwt.jpg",
"https://i.imgur.com/gSTTrhJ.jpg",
"https://i.imgur.com/7RsIJeU.png",
"https://i.imgur.com/YR8WnF5.jpg",
"https://i.imgur.com/MEhe1PS.png",
"https://i.imgur.com/pMwQqGC.jpg",
"https://i.imgur.com/nsUmnqy.jpg",
"https://i.imgur.com/fxlxghy.png",
"https://i.imgur.com/WuAFPSs.jpg",
"https://i.imgur.com/AJvq87S.png",
"https://i.imgur.com/ynJIpCW.jpg",
"https://i.imgur.com/M67gwwy.jpg",
"https://i.imgur.com/BQ435fD.jpg",
"https://i.imgur.com/khlewHB.jpg",
"https://i.imgur.com/La3CtLo.jpg",
"https://i.imgur.com/xDR94w2.jpg",
"https://i.imgur.com/Jwg5j03.png",
"https://i.imgur.com/XKBllmE.jpg",
"https://i.imgur.com/Io3DWlf.jpg",
"https://i.imgur.com/Zufw157.jpg",
"https://i.imgur.com/y8FTavP.png",
"https://i.imgur.com/bxd1tki.png",
"https://i.imgur.com/IuY9yj6.jpg",
"https://i.imgur.com/lf0XTMC.jpg",
"https://i.imgur.com/kn0TegP.png",
"https://i.imgur.com/DZXtPma.png",
"https://i.imgur.com/UpMr1La.jpg",
"https://i.imgur.com/lJf6nb9.jpg",
"https://i.imgur.com/iPxtSQO.png",
"https://i.imgur.com/wuSNTSj.jpg",
"https://i.imgur.com/7ZaWaZx.jpg",
"https://i.imgur.com/PkBbntd.jpg",
"https://i.imgur.com/2ZWwXJM.jpg",
"https://i.imgur.com/ihPSVS6.jpg",
"https://i.imgur.com/1KVXCq7.jpg",
"https://i.imgur.com/IVHpIvz.jpg",
"https://i.imgur.com/jeHvXbA.jpg",
"https://i.imgur.com/B24hQDn.png",
"https://i.imgur.com/3GELHYv.jpg",
"https://i.imgur.com/RaQzRKT.jpg",
"https://i.imgur.com/diCcwY7.jpg",
"https://i.imgur.com/FzneRwK.jpg",
"https://i.imgur.com/RqLDgpw.jpg",
"https://i.imgur.com/YDXsB6O.jpg",
"https://i.imgur.com/JvpyjR4.jpg",
"https://i.imgur.com/faKyr4U.jpg",
"https://i.imgur.com/NxZjGwB.jpg",
"https://i.imgur.com/eRCUXHq.jpg",
"https://i.imgur.com/bf0bnRQ.jpg",
"https://i.imgur.com/m1VzXiq.jpg",
"https://i.imgur.com/rsxv0p4.jpg",
"https://i.imgur.com/48Glefg.png",
"https://i.imgur.com/7iZWHmL.jpg",
"https://i.imgur.com/lA2Be4L.jpg",
"https://i.imgur.com/iSHSFHb.png",
"https://i.imgur.com/NN0FYbx.jpg",
"https://i.imgur.com/C3ch7iM.jpg",
"https://i.imgur.com/wZxN5MP.png",
"https://i.imgur.com/4SjSyE2.jpg",
"https://i.imgur.com/cvYbMaL.jpg",
"https://i.imgur.com/fPScjOK.jpg",
"https://i.imgur.com/yNAuytP.png",
"https://i.imgur.com/BBlMDjo.jpg",
"https://i.imgur.com/UNuWen9.jpg",
"https://i.imgur.com/DoMfTUh.jpg",
"https://i.imgur.com/mjLwkjb.png",
"https://i.imgur.com/Ra1Pmxw.jpg",
"https://i.imgur.com/61uLqsB.jpg",
"https://i.imgur.com/KmqsLT2.jpg",
"https://i.imgur.com/yQDOQqT.png",
"https://i.imgur.com/08czlbf.jpg",
"https://i.imgur.com/rq0RLoh.jpg",
"https://i.imgur.com/08Re9Pb.png",
"https://i.imgur.com/uAE49jV.png",
"https://i.imgur.com/r9sA1n4.png",
"https://i.imgur.com/4K90u6G.jpg",
"https://i.imgur.com/Skagg5t.jpg",
"https://i.imgur.com/egcRvFe.png",
"https://i.imgur.com/MlcU0YD.jpg",
"https://i.imgur.com/WcnBMCe.jpg",
"https://i.imgur.com/ShNU1hk.jpg",
"https://i.imgur.com/iZacX2u.png",
"https://i.imgur.com/JPdFI6e.jpg",
"https://i.imgur.com/fBTDHsu.png",
"https://i.imgur.com/4O7P2ow.png",
"https://i.imgur.com/QpGIkO1.jpg",
"https://i.imgur.com/S2S1J6c.jpg",
"https://i.imgur.com/ZRiCIaU.jpg",
"https://i.imgur.com/oFMfJJV.jpg",
"https://i.imgur.com/kOiSAaK.png",
"https://i.imgur.com/8aj7lj5.jpg",
"https://i.imgur.com/jac4XxO.png",
"https://i.imgur.com/dqnj5q0.png",
"https://i.imgur.com/DY0qOxO.png",
"https://i.imgur.com/fBTwbb0.jpg",
"https://i.imgur.com/JEADzHL.jpg",
"https://i.imgur.com/J3yjjzb.jpg",
"https://i.imgur.com/2a9OHaG.png",
"https://i.imgur.com/W6sS8O2.jpg",
"https://i.imgur.com/dljh5Cw.jpg",
"https://i.imgur.com/sQPmQG3.jpg",
"https://i.imgur.com/WgJUMiw.jpg",
"https://i.imgur.com/9rKvz2P.jpg",
"https://i.imgur.com/q4HhTbB.jpg",
"https://i.imgur.com/w4bBjGE.jpg",
"https://i.imgur.com/Gc5vK3I.png",
"https://i.imgur.com/omlw9vf.jpg",
"https://i.imgur.com/hTHQPtr.jpg",
"https://i.imgur.com/cPZBijH.jpg",
"https://i.imgur.com/Mx9QWp7.jpg",
"https://i.imgur.com/wK1z2yw.jpg",
"https://i.imgur.com/E5Uuuzu.jpg",
"https://i.imgur.com/c5CHFp3.jpg",
"https://i.imgur.com/6ls3vPE.jpg",
"https://i.imgur.com/kXiKNnH.jpg",
"https://i.imgur.com/b34pUjb.jpg",
"https://i.imgur.com/2z0i7vO.png",
"https://i.imgur.com/oaKiiub.jpg",
"https://i.imgur.com/4VYx4AQ.jpg",
"https://i.imgur.com/qohBsMr.jpg",
"https://i.imgur.com/SiCANLo.png",
"https://i.imgur.com/z5ezNQq.jpg",
"https://i.imgur.com/46RzaCC.jpg",
"https://i.imgur.com/VYQVMdC.jpg",
"https://i.imgur.com/w7nBy9T.jpg",
"https://i.imgur.com/xT8s2UA.png",
"https://i.imgur.com/Ecgx7cx.jpg",
"https://i.imgur.com/tzXyVYb.jpg",
"https://i.imgur.com/zgbHgua.png",
"https://i.imgur.com/fHIfq46.png",
"https://i.imgur.com/2HEbcSk.jpg",
"https://i.imgur.com/hl0UM9k.jpg",
"https://i.imgur.com/g6exlzy.jpg",
"https://i.imgur.com/C1mo0F8.jpg",
"https://i.imgur.com/wnZEQ6C.jpg",
"https://i.imgur.com/JYSTDgM.jpg",
"https://i.imgur.com/pP1Sb4K.png",
"https://i.imgur.com/mSZovkh.jpg",
"https://i.imgur.com/6dK21PJ.png",
"https://i.imgur.com/gXAVzyB.jpg",
"https://i.imgur.com/AqTRavP.jpg",
"https://i.imgur.com/JeHFjYq.jpg",
"https://i.imgur.com/KlAyo3H.jpg",
"https://i.imgur.com/tckZNJ2.png",
"https://i.imgur.com/biOzTkh.jpg",
"https://i.imgur.com/rfHL3J7.png",
"https://i.imgur.com/6GwVR0i.png",
"https://i.imgur.com/KlhyOTY.png",
"https://i.imgur.com/Y1YP0rc.png",
"https://i.imgur.com/PZtWLW8.jpg",
"https://i.imgur.com/frVR5c4.jpg",
"https://i.imgur.com/S7IvWnS.png",
"https://i.imgur.com/unGuXDU.png",
"https://i.imgur.com/BBDUquA.png",
"https://i.imgur.com/OuKek2I.png",
"https://i.imgur.com/TRAluay.jpg",
"https://i.imgur.com/SCiceYQ.png",
"https://i.imgur.com/VL8JEtB.png",
"https://i.imgur.com/0kszbFO.png",
"https://i.imgur.com/3TN3P4F.png",
"https://i.imgur.com/EomsB2v.png",
"https://i.imgur.com/XNrOLwu.png",
"https://i.imgur.com/nf6bYqR.png",
"https://i.imgur.com/Xxo9mXY.png",
"https://i.imgur.com/FLNLoKM.png",
"https://i.imgur.com/ouH5G7E.png",
"https://i.imgur.com/EF2bcGh.png",
"https://i.imgur.com/CIWp2nr.png",
"https://i.imgur.com/v1CGU53.jpg",
"https://i.imgur.com/nutYxUg.png",
"https://i.imgur.com/QRh1S0j.jpg",
"https://i.imgur.com/hJo8J69.png",
"https://i.imgur.com/DJcc80I.png",
"https://i.imgur.com/jMWGGk1.jpg",
"https://i.imgur.com/hliMUbw.png",
"https://i.imgur.com/JWtjH76.png",
"https://i.imgur.com/CHeTP0e.jpg",
"https://i.imgur.com/7KASNF7.png",
"https://i.imgur.com/kbzdPqL.png",
"https://i.imgur.com/q0eFGcF.png",
"https://i.imgur.com/LlqnibN.png",
"https://i.imgur.com/CsV9fd6.jpg",
"https://i.imgur.com/86fTh4C.jpg",
"https://i.imgur.com/zwOM6pY.png",
"https://i.imgur.com/nsndhdZ.png",
"https://i.imgur.com/mNQoUcy.jpg",
"https://i.imgur.com/YdX1hn4.png",
"https://i.imgur.com/pSGUtLe.png",
"https://i.imgur.com/L3JkmZ4.png",
"https://i.imgur.com/Yy2PVAR.png",
"https://i.imgur.com/xqwcNh2.jpg",
"https://i.imgur.com/mKl9UKp.png",
"https://i.imgur.com/Z3UGwIJ.png",
"https://i.imgur.com/HpRPsvb.png",
"https://i.imgur.com/U4bB8vV.jpg",
"https://i.imgur.com/5DlnEcQ.png",
"https://i.imgur.com/rFcvLIg.jpg",
"https://i.imgur.com/a1Y7OTq.png",
"https://i.imgur.com/ahUIAXO.png",
"https://i.imgur.com/wb8CNpr.png",
"https://i.imgur.com/pMWeg1J.png",
"https://i.imgur.com/k4Fi6Sb.jpg",
"https://i.imgur.com/KeUDFCa.png",
"https://i.imgur.com/GSWK6gb.png",
"https://i.imgur.com/gixE5KH.jpg",
"https://i.imgur.com/ePQkUDt.png",
"https://i.imgur.com/THLTZNg.jpg",
"https://i.imgur.com/BLYg7iq.png",
"https://i.imgur.com/smhsTBt.png",
"https://i.imgur.com/Ut7jtGc.jpg",
"https://i.imgur.com/D10hCTQ.png",
"https://i.imgur.com/NqKDpqC.png",
"https://i.imgur.com/JAZEIgR.png",
"https://i.imgur.com/fVHyBqL.png",
"https://i.imgur.com/toHLtxN.png",
"https://i.imgur.com/dyJn5a9.png",
"https://i.imgur.com/xLZsp0K.png",
"https://i.imgur.com/5tmHnOA.png",
"https://i.imgur.com/CYkDySN.jpg",
"https://i.imgur.com/aY9Jig3.png",
"https://i.imgur.com/FfVq6jj.png",
"https://i.imgur.com/oIk99E3.png",
"https://i.imgur.com/3fHyK0L.png",
"https://i.imgur.com/xgoECUu.png",
"https://i.imgur.com/NrwZj45.png",
"https://i.imgur.com/0LWjcbT.png",
"https://i.imgur.com/k8jTcxG.png",
"https://i.imgur.com/QTLB2TP.jpg",
"https://i.imgur.com/4xFTxdi.png",
"https://i.imgur.com/tXGS8WK.png",
"https://i.imgur.com/d4O6WDK.png",
"https://i.imgur.com/VC3yHZK.png",
"https://i.imgur.com/IofuMwj.png",
"https://i.imgur.com/5g0Bpcg.png",
"https://i.imgur.com/Wkq0r34.png",
"https://i.imgur.com/uRF3jF3.png",
"https://i.imgur.com/dIOHwJp.png",
"https://i.imgur.com/JbEltT2.jpg",
"https://i.imgur.com/ZY6vcXk.png",
"https://i.imgur.com/Skv5kvi.jpg",
"https://i.imgur.com/mnhnS5V.png",
"https://i.imgur.com/6cqRIRs.png",
"https://i.imgur.com/Fp7DHp1.png",
"https://i.imgur.com/aZft8rx.png",
"https://i.imgur.com/U7JOMDK.png",
"https://i.imgur.com/tzRZqIZ.png",
"https://i.imgur.com/q05GrsM.png",
"https://i.imgur.com/JjXeRnU.png",
"https://i.imgur.com/SISza7s.png",
"https://i.imgur.com/oWefebE.png",
"https://i.imgur.com/PVHGrlz.png",
"https://i.imgur.com/EAVdCXA.png",
"https://i.imgur.com/p6BE8bx.jpg",
"https://i.imgur.com/ACHPxqx.png",
"https://i.imgur.com/nzGzyIm.png",
"https://i.imgur.com/igqoT1b.png",
"https://i.imgur.com/QGVXpT3.png",
"https://i.imgur.com/TT0lS3Q.png",
"https://i.imgur.com/Bgm7xeo.png",
"https://i.imgur.com/8PH5eCw.png",
"https://i.imgur.com/nrq8dCY.jpg",
"https://i.imgur.com/WyoIScj.png",
"https://i.imgur.com/6fNeJD3.png",
"https://i.imgur.com/jzPfSVu.png",
"https://i.imgur.com/bQxXNR1.jpg",
"https://i.imgur.com/jcgjrej.png",
"https://i.imgur.com/ndWHuc4.png",
"https://i.imgur.com/82rB8zX.png",
"https://i.imgur.com/Bw6yBmO.png",
"https://i.imgur.com/1wJY7J9.png",
"https://i.imgur.com/MmA3Ee4.png",
"https://i.imgur.com/hG3xcjv.png",
"https://i.imgur.com/kyVqP3F.jpg",
"https://i.imgur.com/uJoJZDh.png",
"https://i.imgur.com/uvMSFL9.png",
"https://i.imgur.com/JYd0fjy.jpg",
"https://i.imgur.com/UTjInxN.png",
"https://i.imgur.com/oHitvVa.png",
"https://i.imgur.com/smhy73j.png",
"https://i.imgur.com/GyABIVv.png",
"https://i.imgur.com/Y5Bi6Bk.png",
"https://i.imgur.com/AGiL9ar.png",
"https://i.imgur.com/DIOaMyK.png",
"https://i.imgur.com/OAUf5WL.png",
"https://i.imgur.com/SPwBhx1.png",
"https://i.imgur.com/rrxn88k.png",
"https://i.imgur.com/1d03nsg.png",
"https://i.imgur.com/ycDMFPC.png",
"https://i.imgur.com/CHYslAl.png",
"https://i.imgur.com/OuMk5Ek.png",
"https://i.imgur.com/qAwMrrR.png",
"https://i.imgur.com/u5hknfj.png",
"https://i.imgur.com/JGEwfPn.png",
"https://i.imgur.com/LCtnA2x.png",
"https://i.imgur.com/Xu0duL8.png",
"https://i.imgur.com/xzT7cjl.png",
"https://i.imgur.com/FCgyzE3.png",
"https://i.imgur.com/Xpz78MQ.png",
"https://i.imgur.com/2bNJBxC.png",
"https://i.imgur.com/LdgFnAo.png",
"https://i.imgur.com/N8Hg7Dw.png",
"https://i.imgur.com/zEI6yv9.png",
"https://i.imgur.com/U5Wej7l.png",
"https://i.imgur.com/FgiMYpp.png",
"https://i.imgur.com/6PPTf7U.png",
"https://i.imgur.com/s34JMpm.png",
"https://i.imgur.com/ZXihLFN.jpg",
"https://i.imgur.com/Y8Jf2Tp.png",
"https://i.imgur.com/cVnTqHe.png",
"https://i.imgur.com/x8NhJt9.png",
"https://i.imgur.com/pfI4Q75.jpg",
"https://i.imgur.com/iFnzGh4.png",
"https://i.imgur.com/U5JZ04t.png",
"https://i.imgur.com/JtR5Vlo.png",
"https://i.imgur.com/VQKxd9r.png",
"https://i.imgur.com/l8m69iv.png",
"https://i.imgur.com/vAp1Us6.png",
"https://i.imgur.com/pKxduxE.png",
"https://i.imgur.com/2TFQJ7g.png",
"https://i.imgur.com/3k93CRd.png",
"https://i.imgur.com/QQTWUbu.png",
"https://i.imgur.com/apo7YdI.png",
"https://i.imgur.com/C9kI9oE.jpg",
"https://i.imgur.com/AE9ZonR.png",
"https://i.imgur.com/F9Kx2TO.png",
"https://i.imgur.com/n4vGWPH.jpg",
"https://i.imgur.com/PzKW5fz.png",
"https://i.imgur.com/Uxo7KCd.jpg",
"https://i.imgur.com/9QFtKlT.png",
"https://i.imgur.com/xJ2WhHy.png",
"https://i.imgur.com/c22nCrW.png",
"https://i.imgur.com/7tQl5wO.jpg",
"https://i.imgur.com/GWDHHl8.png",
"https://i.imgur.com/wV7TUUT.png",
"https://i.imgur.com/TwYT5mO.jpg",
"https://i.imgur.com/yW9L0FM.png",
"https://i.imgur.com/jnuQBtE.png",
"https://i.imgur.com/pahvLjW.png",
"https://i.imgur.com/jkLrBHh.png",
"https://i.imgur.com/UlsEk4T.png",
"https://i.imgur.com/uk4VpFT.png",
"https://i.imgur.com/FgiWhhj.png",
"https://i.imgur.com/4pKonOw.png",
"https://i.imgur.com/pBE7Fjh.png",
"https://i.imgur.com/VJ2Td7X.png",
"https://i.imgur.com/qFISPYp.png",
"https://i.imgur.com/iUMxn0S.png",
"https://i.imgur.com/V7ai9gC.png",
"https://i.imgur.com/aJFLbmo.png",
"https://i.imgur.com/vWv9R39.png",
"https://i.imgur.com/CpExBq3.png",
"https://i.imgur.com/pgwdHup.png",
"https://i.imgur.com/KrAN4k8.png",
"https://i.imgur.com/M8d5FH3.png",
"https://i.imgur.com/fCV7i8D.png",
"https://i.imgur.com/qjqBDz3.png",
"https://i.imgur.com/61W1nRK.png",
"https://i.imgur.com/IanITfV.png",
"https://i.imgur.com/rUv1aRL.png",
"https://i.imgur.com/fDGGQvK.png",
"https://i.imgur.com/5i0ODRf.png",
"https://i.imgur.com/jtyOSE7.png",
"https://i.imgur.com/ZrISllm.png",
"https://i.imgur.com/1cANqcp.jpg",
"https://i.imgur.com/ig16jUR.png",
"https://i.imgur.com/k7D1B0l.jpg",
"https://i.imgur.com/LW7L0Gt.png",
"https://i.imgur.com/DZcgkW4.png",
"https://i.imgur.com/NmAkMGM.jpg",
"https://i.imgur.com/f7AlojX.png",
"https://i.imgur.com/fFDKAFi.png",
"https://i.imgur.com/feNOpJ0.png",
"https://i.imgur.com/oDKvesY.png",
"https://i.imgur.com/5yUSwr2.png",
"https://i.imgur.com/2HeRMsj.png",
"https://i.imgur.com/WRZuJWx.png",
"https://i.imgur.com/XOJpN8u.png",
"https://i.imgur.com/avSF2QP.png",
"https://i.imgur.com/8v1Enh4.png",
"https://i.imgur.com/nw20xgM.png",
"https://i.imgur.com/zw1KdvX.png",
"https://i.imgur.com/iL8521t.png",
"https://i.imgur.com/z9els2k.png",
"https://i.imgur.com/qhsLHZG.png",
"https://i.imgur.com/b6iWjxl.png",
"https://i.imgur.com/uHNH8jc.png",
"https://i.imgur.com/Pv7fTTP.png",
"https://i.imgur.com/BV9Y50U.png",
"https://i.imgur.com/oj6JwQn.png",
"https://i.imgur.com/SRQEJmG.png",
"https://i.imgur.com/sSSYspM.png",
"https://i.imgur.com/1FYiMtM.png",
"https://i.imgur.com/JA7YTcG.png",
"https://i.imgur.com/DWrpb2h.png",
"https://i.imgur.com/NzlOTSM.jpg",
"https://i.imgur.com/6TwpYTv.png",
"https://i.imgur.com/E28Fiwl.jpg",
"https://i.imgur.com/IxUFbp1.png",
"https://i.imgur.com/JVGrmZE.jpg",
"https://i.imgur.com/Vo5kZGV.jpg",
"https://i.imgur.com/0Z0oIl5.jpg",
"https://i.imgur.com/V2xkwEV.png",
"https://i.imgur.com/QarfMG2.png",
"https://i.imgur.com/8nizpfJ.jpg",
"https://i.imgur.com/1iBYVbJ.png",
"https://i.imgur.com/8Ur9zm1.jpg",
"https://i.imgur.com/JczI76E.jpg",
"https://i.imgur.com/q8Fh31M.jpg",
"https://i.imgur.com/5BIpIoS.png",
"https://i.imgur.com/yhlJlfG.png",
"https://i.imgur.com/zeVyW10.png",
"https://i.imgur.com/wDMoBBA.png",
"https://i.imgur.com/cYy2DFF.jpg",
"https://i.imgur.com/pxHgAkm.jpg",
"https://i.imgur.com/NTUcJSK.jpg",
"https://i.imgur.com/ghJWOe0.jpg",
"https://i.imgur.com/i7Apqe5.png",
"https://i.imgur.com/sK27weu.jpg",
"https://i.imgur.com/zRG81ED.png",
"https://i.imgur.com/DXKiLK3.png",
"https://i.imgur.com/jdt8jhx.png",
"https://i.imgur.com/s6mmJMB.png",
"https://i.imgur.com/FYcLd0C.jpg",
"https://i.imgur.com/zMZlBSK.png",
"https://i.imgur.com/z4rl8KV.jpg",
"https://i.imgur.com/SPLv2rr.png",
"https://i.imgur.com/O4LIHUG.png",
"https://i.imgur.com/rQhpoBn.png",
"https://i.imgur.com/jrq7Zre.png",
"https://i.imgur.com/LZOpIJm.png",
"https://i.imgur.com/3TYGxDR.png",
"https://i.imgur.com/wTUQmMz.png",
"https://i.imgur.com/clOuIRh.png",
"https://i.imgur.com/A7rLpgY.png",
"https://i.imgur.com/gQaFxDg.png",
"https://i.imgur.com/hPOT0Mz.png",
"https://i.imgur.com/CiO1yrh.jpg",
"https://i.imgur.com/bDHTxqX.png",
"https://i.imgur.com/HpXPuSB.png",
"https://i.imgur.com/V0phAy2.png",
"https://i.imgur.com/UzwZYrK.png",
"https://i.imgur.com/hK7jANl.png",
"https://i.imgur.com/6Pzf78q.png",
"https://i.imgur.com/FKkLhT8.png",
"https://i.imgur.com/dLcOOEP.png",
"https://i.imgur.com/OsqRYYE.png",
"https://i.imgur.com/QmFH3s6.png",
"https://i.imgur.com/WMBJEYF.jpg",
"https://i.imgur.com/rrObYoL.png",
"https://i.imgur.com/hByNEn1.jpg",
"https://i.imgur.com/v4mSgwi.jpg",
"https://i.imgur.com/bReDX7j.jpg",
"https://i.imgur.com/czIomMD.png",
"https://i.imgur.com/U4c4ngv.png",
"https://i.imgur.com/bzIIbKB.png",
"https://i.imgur.com/wYx3YN2.png",
"https://i.imgur.com/oKD2i0l.png",
"https://i.imgur.com/FbFMKOR.png",
"https://i.imgur.com/1B4Uhcs.png",
"https://i.imgur.com/z3PohKQ.png",
"https://i.imgur.com/WHvcMgP.png",
"https://i.imgur.com/vRUAVYI.png",
"https://i.imgur.com/OwQfbX8.png",
"https://i.imgur.com/SRsTkZb.png",
"https://i.imgur.com/pDrbwOW.png",
"https://i.imgur.com/D2gEhoT.png",
"https://i.imgur.com/DB2XO7D.png",
"https://i.imgur.com/8Mvd7kz.png",
"https://i.imgur.com/quH1QSR.png",
"https://i.imgur.com/YSpDQqx.png",
"https://i.imgur.com/81sRwWl.png",
"https://i.imgur.com/F01Sxqa.png",
"https://i.imgur.com/8n7wEfF.png",
"https://i.imgur.com/ieOBMS1.png",
"https://i.imgur.com/FAIw7uP.png",
"https://i.imgur.com/mjUht1C.png",
"https://i.imgur.com/x6ByJS2.png",
"https://i.imgur.com/FbsJlHE.png",
"https://i.imgur.com/3qLNy65.png",
"https://i.imgur.com/ovoF2Gm.png",
"https://i.imgur.com/kjZ1Vd9.png",
"https://i.imgur.com/LWZqUb0.png",
"https://i.imgur.com/0ddI72B.png",
"https://i.imgur.com/rtefvbd.png",
"https://i.imgur.com/L4aPcm2.png",
"https://i.imgur.com/pjebFQg.png",
"https://i.imgur.com/YXHMakL.png",
"https://i.imgur.com/VQddeqW.png",
"https://i.imgur.com/P7kIQfG.png",
"https://i.imgur.com/arUuBSh.png",
"https://i.imgur.com/gGekvM3.png",
"https://i.imgur.com/sAs4ZwA.png",
"https://i.imgur.com/YZfhUfJ.png",
"https://i.imgur.com/lJVWp0q.png",
"https://i.imgur.com/3Midwht.png",
"https://i.imgur.com/AlRwZH3.png",
"https://i.imgur.com/cmB01Mj.png",
"https://i.imgur.com/T3RXP57.png",
"https://i.imgur.com/LGJ4eMv.png",
"https://i.imgur.com/6oausWE.png",
"https://i.imgur.com/5WyhEA4.png",
"https://i.imgur.com/hSsAn01.png",
"https://i.imgur.com/rausfhp.png",
"https://i.imgur.com/vszeslG.jpg",
"https://i.imgur.com/oWfxy9P.png",
"https://i.imgur.com/BsZ3fHc.jpg",
"https://i.imgur.com/xd3qeZv.png",
"https://i.imgur.com/SDyGxK6.png",
"https://i.imgur.com/9dMktIV.png",
"https://i.imgur.com/ea5egeW.png",
"https://i.imgur.com/RqfFgzx.png",
"https://i.imgur.com/ASNszyB.png",
"https://i.imgur.com/YdljQHX.png",
"https://i.imgur.com/KGdRzhQ.png",
"https://i.imgur.com/21CmHb9.png",
"https://i.imgur.com/cMC1THG.png",
"https://i.imgur.com/JMUek5U.png",
"https://i.imgur.com/8IxkYNN.png",
"https://i.imgur.com/yMZlQKJ.png",
"https://i.imgur.com/RbD7mEp.png",
"https://i.imgur.com/TQqcmNj.png",
"https://i.imgur.com/o90Nlyi.png",
"https://i.imgur.com/XBJHvVW.jpg",
"https://i.imgur.com/Mvym9fO.jpg",
"https://i.imgur.com/9lE40BL.png",
"https://i.imgur.com/jZgEgBm.png",
"https://i.imgur.com/B3qjdEn.png",
"https://i.imgur.com/slKlH4M.png",
"https://i.imgur.com/QwNYPYT.png",
"https://i.imgur.com/Kp3CFKc.png",
"https://i.imgur.com/7Syfk74.png",
"https://i.imgur.com/cPjmkFM.png",
"https://i.imgur.com/gQAWf9p.png",
"https://i.imgur.com/g1KCtVA.png",
"https://i.imgur.com/Qn6jdMo.png",
"https://i.imgur.com/FfLSbN3.jpg",
"https://i.imgur.com/a9xBAQj.png",
"https://i.imgur.com/CwmLCOu.png",
"https://i.imgur.com/shCgcSO.png",
"https://i.imgur.com/7RS8YUY.png",
"https://i.imgur.com/mRya54z.png",
"https://i.imgur.com/EzgwQ2b.png",
"https://i.imgur.com/Vrutcsq.png",
"https://i.imgur.com/BX6gbCQ.png",
"https://i.imgur.com/I9FrMWl.png",
"https://i.imgur.com/9wXzQFx.png",
"https://i.imgur.com/4CG86gd.png",
"https://i.imgur.com/0IMo1jf.png",
"https://i.imgur.com/Md7KDag.png",
"https://i.imgur.com/AyAv05P.png",
"https://i.imgur.com/cM5If8E.png",
"https://i.imgur.com/wOltfHg.png",
"https://i.imgur.com/XCmUqYQ.png",
"https://i.imgur.com/Q95omiW.png",
"https://i.imgur.com/iJq2l9d.png",
"https://i.imgur.com/lWu8FeB.png",
"https://i.imgur.com/1JWymeE.jpg",
"https://i.imgur.com/HCd1Bz0.png",
"https://i.imgur.com/E5cOy9H.png",
"https://i.imgur.com/5yk9RZL.png",
"https://i.imgur.com/DrbuOom.png",
"https://i.imgur.com/V52G1bk.png",
"https://i.imgur.com/OPbhGOo.png",
"https://i.imgur.com/MglE20b.jpg",
"https://i.imgur.com/SJgasuq.png",
"https://i.imgur.com/RFM1cwt.png",
"https://i.imgur.com/eHPB6qD.png",
"https://i.imgur.com/tS54eUv.png",
"https://i.imgur.com/l0qK42n.png",
"https://i.imgur.com/rWsnTNO.png",
"https://i.imgur.com/hyL9jvK.jpg",
"https://i.imgur.com/7hREYOu.jpg",
"https://i.imgur.com/8povWXz.png",
"https://i.imgur.com/NwqTOzf.png",
"https://i.imgur.com/imsBhTO.png",
"https://i.imgur.com/pgfU1QC.png",
"https://i.imgur.com/koHi5IV.png",
"https://i.imgur.com/W9iDL2z.png",
"https://i.imgur.com/lqHYuH8.png",
"https://i.imgur.com/NWPqea1.png",
"https://i.imgur.com/Ygm1wDQ.png",
"https://i.imgur.com/LzUQUi7.png",
"https://i.imgur.com/bCGhUTb.png",
"https://i.imgur.com/zKaYSql.png",
"https://i.imgur.com/8KWw8IS.png",
"https://i.imgur.com/oeRn47h.png",
"https://i.imgur.com/8Oib2vG.png",
"https://i.imgur.com/N1npsfQ.png",
"https://i.imgur.com/t0vOBEv.png",
"https://i.imgur.com/bMl8tPt.png",
"https://i.imgur.com/SmnChOY.png",
"https://i.imgur.com/0CcSCZZ.png",
"https://i.imgur.com/5HSqsWa.png",
"https://i.imgur.com/9qoTxjQ.png",
"https://i.imgur.com/rA4ADYe.png",
"https://i.imgur.com/fp37k10.png",
"https://i.imgur.com/tCxsiGv.png",
"https://i.imgur.com/tITUwje.png",
"https://i.imgur.com/szer5xX.png",
"https://i.imgur.com/EzpYM7j.png",
"https://i.imgur.com/I8O87Zu.png",
"https://i.imgur.com/WlOICa1.png",
"https://i.imgur.com/zFwC9Qi.png",
"https://i.imgur.com/MVDFqNs.png",
"https://i.imgur.com/p2avECj.jpg",
"https://i.imgur.com/mlfPbGz.png",
"https://i.imgur.com/brs9dq7.png",
"https://i.imgur.com/Vg7RkpO.png",
"https://i.imgur.com/sAIMsZr.png",
"https://i.imgur.com/5eoKqFA.png",
"https://i.imgur.com/dRc2dGc.png",
"https://i.imgur.com/VEoIIY4.jpg",
"https://i.imgur.com/NVNmJqq.png",
"https://i.imgur.com/J0AvAnr.png",
"https://i.imgur.com/sPNiObA.png",
"https://i.imgur.com/slhgGKl.png",
"https://i.imgur.com/4rYISLq.jpg",
"https://i.imgur.com/Wx1Ttd9.png",
"https://i.imgur.com/FchBaOR.png",
"https://i.imgur.com/K0zon7W.png",
"https://i.imgur.com/KJ0bQQy.png",
"https://i.imgur.com/0xLeQ3i.png",
"https://i.imgur.com/n7AVLXJ.png",
"https://i.imgur.com/NOxSzCl.png",
"https://i.imgur.com/Px7QBUa.png",
"https://i.imgur.com/I8W5vaK.png",
"https://i.imgur.com/ZVKwzjQ.png",
"https://i.imgur.com/jLO151e.png",
"https://i.imgur.com/sGGlIG1.jpg",
"https://i.imgur.com/6tHzQVm.png",
"https://i.imgur.com/o1DrSYg.png",
"https://i.imgur.com/mkEzLEM.png",
"https://i.imgur.com/49epnFA.png",
"https://i.imgur.com/H4Sb1EK.jpg",
"https://i.imgur.com/5obokgb.png"];
  
  
  
    
var countkarabita = Math.round(Math.random() * (2 - 1) + 1)
var randomkarabitapic = ["0",
"https://78.media.tumblr.com/d3243b5a3c601dd0873f730fdf865237/tumblr_p5keajjxaW1u9l2uco2_r1_1280.png"];

var randomkarabitasourceicon = ["0",
"https://78.media.tumblr.com/avatar_0f3c654409dd_128.png"];

var randomkarabitasource = ["0",
"source:bothriolepis"];

var randomkarabitasourcelink = ["0",
"http://bothriolepis.tumblr.com/post/171856220840/gorlfriends"];


  

  

const KARMO = new Discord.RichEmbed()
   /*
   * Alternatively, use "#00AE86", [0, 174, 134] or an integer number.
   */
  .setColor(0x36393E)
  .setImage(randomkara[count]);
  

 
const KARABITATA = new Discord.RichEmbed()
  .setColor(0x36393E)
  .setImage(randomkarabitapic[countkarabita])
  
  .setAuthor(randomkarabitasource[countkarabita], randomkarabitasourceicon[countkarabita])
  .setUrl(randomkarabitasourcelink[countkarabita]);
  
  
  
  if (message.content.startsWith(prefix + "kara"))  {
    
       if (message.content.startsWith(prefix + "karabita"))  {
message.channel.sendEmbed(KARABITATA);
}  
    else message.channel.sendEmbed(KARMO);
}



  

  
  
  
  
  
  
  
  
  
  var countkinniku = Math.round(Math.random() * (50 - 1) + 1)
var randomkinniku = ["https://i.imgur.com/Rj8wuJ7.jpg",
"https://i.imgur.com/VMsXNkW.png",
"https://i.imgur.com/iVwbxoJ.png",
"https://i.imgur.com/f5TV83W.png",
"https://i.imgur.com/UgIIB6a.png",
"https://i.imgur.com/95cSIzR.png",
"https://i.imgur.com/qAljy3Q.png",
"https://i.imgur.com/P6jsUxl.png",
"https://i.imgur.com/1MRbhvP.png",
"https://i.imgur.com/c5uTbyW.png",
"https://i.imgur.com/uXXC66y.png",
"https://i.imgur.com/QjI4cWd.png",
"https://i.imgur.com/Hr8xsS0.png",
"https://i.imgur.com/5W74v4f.png",
"https://i.imgur.com/qg8yAPq.png",
"https://i.imgur.com/B6GkdDr.png",
"https://i.imgur.com/4SsxCDi.png",
"https://i.imgur.com/dthm32j.png",
"https://i.imgur.com/FkF4VFu.png",
"https://i.imgur.com/vUNzLoD.png",
"https://i.imgur.com/rlaUHkm.png",
"https://i.imgur.com/XphfuVE.png",
"https://i.imgur.com/H0Nut7E.png",
"https://i.imgur.com/GaHPzCc.png",
"https://i.imgur.com/nVBujJN.png",
"https://i.imgur.com/jVI3ojw.png",
"https://i.imgur.com/7zoqvdb.png",
"https://i.imgur.com/r8qMPYh.png",
"https://i.imgur.com/Ht5efkf.png",
"https://i.imgur.com/7fGAr3l.png",
"https://i.imgur.com/ghXrYI0.png",
"https://i.imgur.com/9itcVn1.png",
"https://i.imgur.com/Q0FO7ff.png",
"https://i.imgur.com/QUgCvb4.png",
"https://i.imgur.com/7vQPAtQ.png",
"https://i.imgur.com/CUJO0Cx.png",
"https://i.imgur.com/6w72UPn.gifv",
"https://i.imgur.com/yjSd6QD.png",
"https://i.imgur.com/xEJsCI6.png",
"https://i.imgur.com/tkdFhxH.png",
"https://i.imgur.com/GRDURu5.gifv",
"https://i.imgur.com/zBa0MgX.png",
"https://i.imgur.com/D2SdYkH.png",
"https://i.imgur.com/53bC05W.png",
"https://i.imgur.com/mXwQoBY.png",
"https://i.imgur.com/Y1iMsW8.png",
"https://i.imgur.com/3zeRoiw.png",
"https://i.imgur.com/yDcchfU.gifv",
"https://i.imgur.com/UUoHYmL.png",
"https://i.imgur.com/aqaXvx0.png"];

const KINNIKUKU = new Discord.RichEmbed()
   /*
   * Alternatively, use "#00AE86", [0, 174, 134] or an integer number.
   */
  .setColor(0x36393E)
  .setImage(randomkinniku[countkinniku]);
  

  
  
  
  if (message.content.startsWith(prefix + "kinniku"))  {
message.channel.sendEmbed(KINNIKUKU);
}
  
  
  
  
 var countchibi = Math.round(Math.random() * (53 - 1) + 1)
var randomchibi = ["https://i.imgur.com/CC1JUOX.jpg",
"https://i.imgur.com/b1tIOVI.jpg",
"https://i.imgur.com/HkvyqtB.jpg",
"https://i.imgur.com/BcnVFkX.jpg",
"https://i.imgur.com/hp9AMZL.jpg",
"https://i.imgur.com/bW2gqxd.jpg",
"https://i.imgur.com/j9jCF4l.jpg",
"https://i.imgur.com/b5aMOSx.jpg",
"https://i.imgur.com/VjkBeyD.jpg",
"https://i.imgur.com/MthBzJ5.jpg",
"https://i.imgur.com/1lP7QPI.jpg",
"https://i.imgur.com/Np9Rm94.jpg",
"https://i.imgur.com/2kG7hsf.jpg",
"https://i.imgur.com/rrS7gBw.jpg",
"https://i.imgur.com/pbmBnpu.jpg",
"https://i.imgur.com/Yx5oUNG.jpg",
"https://i.imgur.com/SiupbOY.jpg",
"https://i.imgur.com/THquYlh.png",
"https://i.imgur.com/w68ZKZT.jpg",
"https://i.imgur.com/CpgSHbb.jpg",
"https://i.imgur.com/x20GmvD.jpg",
"https://i.imgur.com/X2q7cht.png",
"https://i.imgur.com/OmMRblu.jpg",
"https://i.imgur.com/k9wl3fV.jpg",
"https://i.imgur.com/15T0MXs.jpg",
"https://i.imgur.com/uTEp9iC.jpg",
"https://i.imgur.com/IeN0JV1.jpg",
"https://i.imgur.com/k8KQhoe.jpg",
"https://i.imgur.com/H9HCIxB.jpg",
"https://i.imgur.com/tRawRaU.jpg",
"https://i.imgur.com/zyp8FXw.png",
"https://i.imgur.com/Eyi2fui.jpg",
"https://i.imgur.com/oPjGpM8.jpg",
"https://i.imgur.com/dXdGf5K.jpg",
"https://i.imgur.com/NDMYuHr.jpg",
"https://i.imgur.com/HV5olDf.jpg",
"https://i.imgur.com/rOI4KpB.jpg",
"https://i.imgur.com/YqCMSVB.jpg",
"https://i.imgur.com/qLY3O6J.png",
"https://i.imgur.com/jsJVKrW.png",
"https://i.imgur.com/kJYFtyQ.jpg",
"https://i.imgur.com/XtZ2QGr.jpg",
"https://i.imgur.com/5JlTGpd.png",
"https://i.imgur.com/zhZbHiR.gifv",
"https://i.imgur.com/BssbTPC.png",
"https://i.imgur.com/iDxsOpW.png",
"https://i.imgur.com/0FKwg2N.gifv",
"https://i.imgur.com/4hGf3cU.png",
"https://i.imgur.com/tdmNkAs.png",
"https://i.imgur.com/0cPGtFw.png",
"https://i.imgur.com/sbWUaSV.gifv",
"https://i.imgur.com/6tNyt9b.png",
"https://i.imgur.com/1CeRrpn.png",
"https://i.imgur.com/nWbYfn6.png",
"https://i.imgur.com/FvlmRKv.png",
"https://i.imgur.com/KiSwe7g.png"];

const CHIBITATA = new Discord.RichEmbed()
   /*
   * Alternatively, use "#00AE86", [0, 174, 134] or an integer number.
   */
  .setColor(0x36393E)
  .setImage(randomchibi[countchibi]);
  
  
  
  if (message.content.startsWith(prefix + "chibita"))  {
message.channel.sendEmbed(CHIBITATA);
}
  
  
var countoso = Math.round(Math.random() * (142 - 1) + 1)
var randomoso = ["https://i.imgur.com/Ws9wHn7.jpg",
"https://i.imgur.com/3nbpz7p.jpg",
"https://i.imgur.com/GdX4kaG.jpg",
"https://i.imgur.com/9lRAtP0.png",
"https://i.imgur.com/MMmAWwc.png",
"https://i.imgur.com/d8GCqT5.png",
"https://i.imgur.com/TqL6xs5.png",
"https://i.imgur.com/ULLNxIf.png",
"https://i.imgur.com/s4mc3Fs.png",
"https://i.imgur.com/xuRELqP.jpg",
"https://i.imgur.com/sXd77YQ.png",
"https://i.imgur.com/kJtbdvJ.png",
"https://i.imgur.com/7MsCesw.png",
"https://i.imgur.com/UvluST8.png",
"https://i.imgur.com/oKW7vJ2.png",
"https://i.imgur.com/Si2SP6n.png",
"https://i.imgur.com/Cjrb0Q0.png",
"https://i.imgur.com/ayYkGBm.png",
"https://i.imgur.com/QjCCc3b.png",
"https://i.imgur.com/UDpjRJh.png",
"https://i.imgur.com/gnGGROD.png",
"https://i.imgur.com/npcAMVy.png",
"https://i.imgur.com/MlyIlFu.png",
"https://i.imgur.com/Ej63i0Q.png",
"https://i.imgur.com/G2V8bzl.png",
"https://i.imgur.com/lIUEStM.png",
"https://i.imgur.com/SkbbImG.png",
"https://i.imgur.com/QXej2tw.png",
"https://i.imgur.com/jrNjp58.png",
"https://i.imgur.com/8va4SJq.png",
"https://i.imgur.com/WcQoViT.png",
"https://i.imgur.com/pj5wvgX.png",
"https://i.imgur.com/5ZlvReK.png",
"https://i.imgur.com/GrsKzTw.png",
"https://i.imgur.com/yJ7n5CY.png",
"https://i.imgur.com/rrlxCiX.png",
"https://i.imgur.com/8DXKcet.png",
"https://i.imgur.com/FE1Hu0d.png",
"https://i.imgur.com/cdVUJso.png",
"https://i.imgur.com/myXKUsM.png",
"https://i.imgur.com/mVYKbqV.png",
"https://i.imgur.com/aVlHT7a.png",
"https://i.imgur.com/Jsp30H6.png",
"https://i.imgur.com/FhwWgbu.png",
"https://i.imgur.com/fV1G1hx.png",
"https://i.imgur.com/Z4qL3GI.png",
"https://i.imgur.com/pvoKnCJ.png",
"https://i.imgur.com/5wIV2GC.png",
"https://i.imgur.com/RlUJBpE.png",
"https://i.imgur.com/z5Bg8Wb.png",
"https://i.imgur.com/OURrzO5.png",
"https://i.imgur.com/3dipj6W.png",
"https://i.imgur.com/ZjTUJfw.png",
"https://i.imgur.com/XTqS6lS.png",
"https://i.imgur.com/XfF4UTT.png",
"https://i.imgur.com/jT4qsFE.png",
"https://i.imgur.com/kSmGlzo.png",
"https://i.imgur.com/5WSoVUR.png",
"https://i.imgur.com/VdCPGiu.png",
"https://i.imgur.com/P1Rg0qs.png",
"https://i.imgur.com/VVzk6IC.png",
"https://i.imgur.com/wJEi5dW.png",
"https://i.imgur.com/latHrqJ.png",
"https://i.imgur.com/uiofF6J.png",
"https://i.imgur.com/K1ZiBkj.png",
"https://i.imgur.com/iYTC7CI.png",
"https://i.imgur.com/IREFCTh.png",
"https://i.imgur.com/Pdr3o0l.png",
"https://i.imgur.com/XA6VHOw.png",
"https://i.imgur.com/Vn8pe03.png",
"https://i.imgur.com/b5griq0.png",
"https://i.imgur.com/1yQv1hc.png",
"https://i.imgur.com/CBEWRex.png",
"https://i.imgur.com/8jEkJcx.png",
"https://i.imgur.com/aiGs9No.png",
"https://i.imgur.com/YtSEba5.png",
"https://i.imgur.com/NzevKcE.png",
"https://i.imgur.com/ZDsjRQ2.png",
"https://i.imgur.com/zedNwVp.png",
"https://i.imgur.com/DLWEbfV.png",
"https://i.imgur.com/1XPdM4D.png",
"https://i.imgur.com/W7dmFrs.png",
"https://i.imgur.com/w2ZJLEo.png",
"https://i.imgur.com/ULi5Vsk.png",
"https://i.imgur.com/XtKJfiC.png",
"https://i.imgur.com/swlCJhQ.png",
"https://i.imgur.com/AQtXenE.png",
"https://i.imgur.com/rOj7tGO.png",
"https://i.imgur.com/qrVWbg5.png",
"https://i.imgur.com/9j0QfQd.png",
"https://i.imgur.com/dKbbETl.png",
"https://i.imgur.com/17cYK3Z.png",
"https://i.imgur.com/XmfjC9U.png",
"https://i.imgur.com/pl0LUgT.png",
"https://i.imgur.com/5ovVDQ7.png",
"https://i.imgur.com/vqgw7bv.png",
"https://i.imgur.com/80zIY22.png",
"https://i.imgur.com/ppCexzQ.png",
"https://i.imgur.com/br8tfsE.png",
"https://i.imgur.com/pvkJL84.png",
"https://i.imgur.com/lux68LB.png",
"https://i.imgur.com/VmeySBY.png",
"https://i.imgur.com/rbd3FA9.png",
"https://i.imgur.com/pJ5o7h8.png",
"https://i.imgur.com/mBtqkpk.png",
"https://i.imgur.com/diXQZFL.png",
"https://i.imgur.com/26sXGLM.png",
"https://i.imgur.com/J1zkIi0.png",
"https://i.imgur.com/EIgV28g.png",
"https://i.imgur.com/NfJmPK3.png",
"https://i.imgur.com/eiAlaAk.png",
"https://i.imgur.com/xjl98Zb.png",
"https://i.imgur.com/W7cUrA3.png",
"https://i.imgur.com/tEwdZcy.png",
"https://i.imgur.com/lDImGFD.png",
"https://i.imgur.com/8DNNh4W.png",
"https://i.imgur.com/K1qe5Wn.png",
"https://i.imgur.com/ZgtGjcF.png",
"https://i.imgur.com/qaXLRLd.png",
"https://i.imgur.com/GmYr1vR.png",
"https://i.imgur.com/3LTlj6T.png",
"https://i.imgur.com/prrfxeO.png",
"https://i.imgur.com/ydt3w1G.png",
"https://i.imgur.com/aXhciwi.png",
"https://i.imgur.com/aDC4iyf.png",
"https://i.imgur.com/k81uiqq.png",
"https://i.imgur.com/9W4pQ3M.png",
"https://i.imgur.com/W2s1mqp.png",
"https://i.imgur.com/NyHn6Pk.png",
"https://i.imgur.com/BtVrMqZ.png",
"https://i.imgur.com/SMKWyvD.png",
"https://i.imgur.com/GykQ7GJ.png",
"https://i.imgur.com/jlxe9xr.png",
"https://i.imgur.com/94Xmv1k.png",
"https://i.imgur.com/bwlpEnt.png",
"https://i.imgur.com/DYgqaHL.png",
"https://i.imgur.com/tWo56Eh.png",
"https://i.imgur.com/cR7lkdd.png",
"https://i.imgur.com/wYILh5m.png",
"https://i.imgur.com/gsPya05.png",
"https://i.imgur.com/NbNbe06.png",
"https://i.imgur.com/OcNWTKA.png",];

const OSOSO = new Discord.RichEmbed()
   /*
   * Alternatively, use "#00AE86", [0, 174, 134] or an integer number.
   */
  .setColor(0x36393E)
  .setImage(randomoso[countoso]);
  
  
  
  if (message.content.startsWith(prefix + "oso"))  {
message.channel.sendEmbed(OSOSO);
}  
  
  
  
  
  

var domymath2 = Math.round(Math.random() * (9 - 1) + 1)
var myArray2 = ['0a',
              'heh',
              '*heh*',
              '*he h*',
              '**h e h** :sparkles:',
              '**heh** ',
              'heh.. .',
              ':sparkles: **H E H** :sparkles:',
              ':regional_indicator_h: :regional_indicator_e: :regional_indicator_h:',
              '***HEH***'];

  if (message.content.startsWith(prefix + "heh"))  {
message.channel.sendMessage(myArray2[domymath2]);
}

 if (message.content.startsWith(prefix + "clap"))  {
   var menos=message.cleanContent.replace("cb!clap", "")
    var clappy= menos.toUpperCase().replace(/ /g," :clap: ")
message.channel.sendMessage(clappy + " :clap: ");
}


});








bot.login(process.env.BOT_TOKEN);
